- name: Create the directory
  become: yes
  file: path=/data/cassandra/backup state=directory recurse=yes

- name: copy the backup script
  become: yes
  template: src=cassandra_backup.j2  dest=/data/cassandra/backup/cassandra_backup.py mode=0755

- set_fact:
    cassandra_backup_gzip_file_name: "cassandra-backup-{{ lookup('pipe', 'date +%Y%m%d') }}-{{ ansible_hostname }}"

- set_fact:
    cassandra_backup_gzip_file_path: "{{ cassandra_backup_dir }}/{{ cassandra_backup_gzip_file_name }}.tar.gz"

- name: run the backup script
  become: yes
  shell: python cassandra_backup.py --snapshotname "{{ cassandra_backup_gzip_file_name }}"
  args:
    chdir: /data/cassandra/backup
  async: 7200
  poll: 30

- name: Check doc_root path
  shell: ls -all /data/cassandra/backup/
  register: doc_data

- name: print doc_root to console
  debug:
    var: doc_data

- name: Uploading to S3
  command: aws s3 cp "{{ cassandra_backup_gzip_file_name }}".tar.gz s3://sl-production-db-backups/"{{ cassandra_backup_gzip_file_name }}".tar.gz
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key | d('')}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_key | d('')}}"
    AWS_DEFAULT_REGION: "{{aws_region | d('')}}"
  async: 3600
  poll: 10

- name: clean up backup dir after upload
  file: path="{{ cassandra_backup_dir }}" state=absent
